name: Claim Free Games

on: # When to run this workflow
    push: # When you edit this repo

# Uncomment the below lines to enable manual trigger.

#    watch:
#        types: [started] # When repo owner stars this repo

    schedule:
        - cron: "48 18 * * *" # Everyday at 00:00 UTC

jobs:
    claim:
        runs-on: ubuntu-latest

        timeout-minutes: 5 # Automatically stop after 5 minutes

        steps:
            - name: Setup repo
              uses: actions/checkout@v2
              with:
                  repository: "Revadike/epicgames-freebies-claimer"

            - name: Setup Node.js
              uses: actions/setup-node@v1

            - name: Install dependencies
              run: yarn

            - name: Hotfix for \#4 # https://github.com/xuac/claim-epic-freebies/issues/4
              run: mkdir .egstore

            - name: Fix launch the browser
              run: sudo apt-get install -y xvfb & sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf & sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable & Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99 

            - name: Get Epic Freebies
              run: yarn start ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} 0 ${{ secrets.SECRETKEY }}
